name: Testing Github Actions
defaults:
  run:
    shell: bash
    working-directory: build_tests/test_compile/build
on: push
jobs: 
  compile-code:
    name: Test compilation of code
    runs-on: ubuntu-latest
    container: 
      image: hamishi/fortran-netcdf
    steps:      
      - uses: actions/checkout@v3
      - run: cmake ..
      - run: make 
