name: Testing Github Actions
on: workflow_dispatch
jobs: 
  compile-code:
    name: Test compilation of code
    runs-on: ubuntu-latest
    container: 
      image: hamishi/fortran-netcdf
      volumes:
        - ${{ github.workspace }}
    steps:
      - run: ls
      - run: cd fortran/build
      - run: cmake ..
