name: Testing Github Actions
on: [push]
jobs: 
  compile-code:
    name: Test compilation of code
    runs-on: ubuntu-latest
    container: 
      image: hamishi/netcdf-fortran
      volumes:
        - ${{ github.workspace }}
    steps:
      - run: cd fortran/build
      - run: cmake ..
