name: Testing Github Actions
on: push
jobs: 
  compile-code:
    name: Test compilation of code
    runs-on: ubuntu-latest
    container: 
      image: hamishi/fortran-netcdf
      volumes:
        - ${{ github.workspace }}:/test
    steps:
      - run: /bin/ls
      - run: cd fortran/build
      - run: cmake ..
